modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Lykrast/Voyage/issues"
license="https://github.com/Lykrast/Voyage/blob/master/LICENSE"
[[mods]]
modId="voyage"
version="${version}"
displayName="Voyage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/voyage"
credits="Voyage for the idea of a lightweight biome mod"
authors="Lykrast"
description='''
A lightweight biome mod that adds more biomes to your game without adding anything that isn't a biome, like blocks or items.
'''

[[dependencies.voyage]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.voyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
